### ISSUE TITLE
The program got stuck when "Performing exhaustive search to add migration edge to base tree"

### ISSUE THREAD

**Issue by ZheCai** [sriramlab/OrientAGraph#7]
Hi,

I found the program often got stuck when migration edges more than 6. The output log has never refreshed for many days after printing "Performing exhaustive search to add migration edge to base tree". I'm sure the program is still running (%CPU is 100%), but no output anymore.

Is this a bug? Or it's a problem due to my data?

Thanks!

**Comment by ekmolloy** [comment]
Hello,

How many populations (leaf nodes) do you have? During the orientation step, we evaluate the likelihood of O(n choose 5) orientations, where n is the number of populations. If n is 50, this is 2,118,760 combinations. This could take a long time. However, it's also possible the program is stuck. I will add a message so that you can check.

Thanks!
-Erin

**Comment by ekmolloy** [comment]
Note that you had -m 5 in your last message so I am assuming you still have 5. If you have 6, then this would O(n choose 6) which is 15,890,700 combinations for n - 50. In this case, it seems unlikely to complete. I recommend using -mlno 4, which will only perform orientation for the first 4 admixture edge additions. Thanks!

**Comment by ZheCai** [comment]
I have 7 pops for running (including one Outgroup pop). Only two runs (with m=7) have normal output in ten replicates.

Thanks for your suggestion, I will have a try with the -mlno option.

**Comment by ekmolloy** [comment]
OrientAGraph and methods based on the same approximate likelihood function (e.g., TreeMix) are unlikely to work with 7 populations and 7 migration edges. I recommend reading Mark Lipson's 2020 review (download here: https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.13230) and then counting the number of knowns vs. unknowns. Another good check is to run the original TreeMix method and to see if it quits without adding all seven migration edges. I will look into adding an error message to OrientAGraph rather than it stalling out.

**Comment by ZheCai** [comment]
According to the paper, there doesn't seem to be enough constraints for 7 migration edges among 7 pops, and the most number of migration edges should be 5 for seven pops if I understand correctly.

Your suggestions are extremely informative. I'm most grateful for your help!

**Comment by ekmolloy** [comment]
Happy to help! :) This is a common challenge - so I will try to make it so that OrientAGraph throws an informative error message in this situation rather than getting stuck.
